packages:
  - name: api
    functions:
      - name: __main__
        runtime: 'python:default'
        web: true
        environment:
          OPENAI_API_KEY: ${OPENAI_API_KEY}
          GITHUB_TOKEN: ${GITHUB_TOKEN}
          QDRANT_URL: ${QDRANT_URL}